### ISSUE TITLE
Use Doxygen instead of custom documentation generator

### ISSUE THREAD

**Issue by aviallon** [allegroflare/allegro_flare#168] opened 2019-10-25 22:46 UTC
Doxygen has the advantage that it is very portable, is maintained, and forces you to explain what functions / classes do in the source code, which makes source code far easier to read.

#169

**Comment by MarkOates** [comment] 2019-10-26 01:16
On this one, I hate to be a party pooper but I have a strong opinion _against_ Doxygen and other code generation tools like it.

I understand the advantages, and I appreciate the efforts so far on the PR, but before you get much further you should know that the primary disadvantage for me is how the documentation format couples with the source code.  I'm also not a fan of the format of Doxygen's DSL, or the documentation format that it generates, and so we'll need to find a different solution.

The main reason I started the [Documentation Project](https://github.com/allegroflare/allegro_flare/blob/master/documentation/build_scripts/README.md) was to bootstrap something that would allow the source code to be independent from the documentation.  I admit it's very early in that project (or find something similar that can produce similar results) and for the time being, I'd prefer to continue developing on that.  I do think it has a lot of potential to fit the needs for the documentation format more nicely.  I should note that one of the [primary requirements of that project](https://github.com/allegroflare/allegro_flare/tree/master/documentation/build_scripts#what-features-must-it-include) is the documentation must be decouped from the source code.

**Comment by aviallon** [comment] 2019-10-27 11:49
That is actually very debatable. Having documentation inside source code is very helpful, whereas having a custom script for that is not very portable. Perhaps using a standard tool for external documentation generation would be a good compromise?

**Comment by MarkOates** [comment] 2019-10-27 17:47
> Having documentation inside source code is very helpful

My position on this is that the source code should be absent of comments almost entirely.  Code should be written in a way that is easily interpretable by reading the code. This means great identifier names, sections of code split up into small meaningful paragraphs, isolated single responsibility functionality, all of the good habits in code writing - I could go on, this is one of my favorite things.

All the commenting [included in `Useful.hpp`](https://github.com/allegroflare/allegro_flare/blob/master/include/AllegroFlare/Useful.hpp) was a challenge to myself to experiment with the contrary to my position. I tried to create the cleanest possible in-code comment strategy I could conceptualize, but even after that absolute minimal documentation footprint, I find it more difficult to locate code in question during development, and have never once actually looked at the comments.

Other issues with in-code documentation include 1) documentation interfering with code search, 2) changes in inlined-documentation signalling code changes in git commits, 3) in-code comments interfering with auto-generating code tools (as is done more frequently with my very fancy [quintessence extrapolation](https://github.com/MarkOates/blast/blob/master/documentation/quintessence.md), 4) and just in general all the problems that come along with coupling tools together, causing headaches with upgrades, depreciations, and the like.  In short, the documentation will have to stand independent.

> Perhaps using a standard tool for external documentation generation would be a good compromise?

Absolutely! If a decent one exists.  I haven't found one unfortunately.

I do have a lot of experience with web (most of which I've gained _after_ since starting the [Documentation Project](https://github.com/allegroflare/allegro_flare/blob/master/documentation/build_scripts/README.md), so there's a lot to improve there) and to me the problem is not a difficult one to solve.  Just gotta figure out the right tools so it's just dead simple to create or modify new entries, and produce a really premium documentation experience.

If someone wanted to generate the docs locally, it would be good for them to be able to without much woe.  In theory, docs are online and would be downloadable in their entirety, and a user shouldn't have to worry about generating them unless they wanted to work in development.  Documentation could be included in a package with the library, as a possible option as well.

### New Database Format

One thing I _definitely_ want to do is get rid of `sqlite` as the documentation database format.  That's messy and squirly and has annoying dependencies, and the DSL for sqlite is not similar to other language tools, requires a learning curve and is cumbersome and messy, not to mention the documentation records themselves are not transparent at all.  As far as using `sqlite` as the database format, that much at least was a terrible solution.

Truly the best database technique I know of is simply the usage of `yaml` files in the repo.  This allows for simpler access of the records, fully transparent documentation records, and a completely stripped down and minimal set of properties to define. The `yaml` format that has a lot of support and tools in each language, and most importantly it's dead simple.  In this format, anybody would easily submit documentation without interferring with code development, and it even would be conceivable to request/support translations into different languages, which is something I want to have baked in from the beginning.

As an example of what that might look like, I've created a branch with a with a single doc entry for the `AllegroFlare/Achievement` component.  The entry exists in `documentation/AllegroFlare/Achievement.doc.yml`, paralleling perfectly the folder structure of source, include, and test files for that component.  It wouldn't be hard to verify/validate that entries are present with a simple script.

Here's that branch: https://github.com/allegroflare/allegro_flare/compare/alternative-documentation-format

With something like that in place, the path to developing document compilation scripts (or even using 3rd party solutions) would be more clear.  These records could even be imported as [`FrozenRecord`](https://github.com/byroot/frozen_record) in Rails if that became a thing.

**Comment by aviallon** [comment] 2019-10-27 21:32
Interesting. Just so you know, Doxygen can also be used to generate documentation without having comments in the code. But there won't be specific messages explaining what a function does.

>  Code should be written in a way that is easily interpretable by reading the code.

On that I do agree. But : 
> causing headaches with upgrades, deprecations, and the like. In short, the documentation will have to stand independent.
I actually experienced the exact opposite... (hence my position on **Doxygen style** comments above functions.
> I find it more difficult to locate code in question during development, and have never once actually looked at the comments.
Perhaps because their structure is not really clear. Doxygen comments have a standard syntax. They must be extremely concise. And what doesn't need to be documented shall not be.
I will share you an example of some of my code on a similar project, so that you can understand what I mean. Briefs shall not be used for functions that do not need it.

In the end : code should be very clear so that you can understand what's going on without relying on comments. BUT database-based documentation are **unmaintainable** on big projects with multiple developers. When it is in the code itself, you won't forget to add your new class to the doc. And you won't forget to modify it either.

**Comment by MarkOates** [comment] 2020-09-13 01:46
Thanks for the discussion.  A lot of good points.

I'm going to close the issue since it's been almost a year and all the points have been made.

**Closed by MarkOates** 2020-09-13 01:46 UTC
